In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [3]:
print(arr[4:])

[5 6 7]


In [4]:
print(arr[:4])

[1 2 3 4]


In [5]:
print(arr[-3:-1])

[5 6]


In [6]:
print(arr[1:5:2])

[2 4]


In [7]:
print(arr[::3])

[1 4 7]


In [23]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:1, 1:4])

[[2 3 4]]


In [18]:
print(arr[0:2, 2])

[3 8]
